research_task:
  description: >
    Conduct an in-depth research about {topic}, focusing on the most recent and relevant developments.
    Prioritize high-authority sources, official reports, and peer-reviewed studies.
    Ensure that the information is up to date for the current year ({current_year}).
  expected_output: >
    A structured list with 10 key insights about {topic}, each with a short summary and a source link when available.
  agent: researcher

reporting_task:
  description: >
    Review the research findings and expand each key insight into a well-structured report.
    Ensure the report provides context, explanations, and any relevant data points.
    The final report should be easy to understand, detailed, and actionable.
  expected_output: >
    A fully structured report in markdown format (excluding '```'), with a clear introduction, main sections for each key insight, 
    and a concluding summary highlighting key takeaways.
  agent: reporting_analyst
